<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Defaultpage.aspx.cs" Inherits="WebApplication1.Defaultpage" %>



 <asp:Content ID="Content1" runat="server" contentplaceholderid="ContentPlaceHolder1">
     <asp:Button ID="Button1" runat="server" Text="Invoice List" OnClick="Button1_Click1" Height="31px" Width="435px" />
     <asp:Button ID="Button2" runat="server" Text="Buyers" OnClick="Button2_Click1" Height="31px" Width="405px" />
     <asp:Button ID="Button3" runat="server" Text="Invoice Addition" OnClick="Button3_Click" Height="31px" Width="420px" />
         <br />
         <br />
     <br />
     <br />    
     
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<asp:Chart ID="Chart5" runat="server" Width="582px">
         <Titles>
        <asp:Title Font="Times New Roman, 12pt, style=Bold, Italic" Name="Title1" 
            Text="Customers based on Region">
        </asp:Title>
    </Titles>
         <Series>
             <asp:Series Name="Series1">
             </asp:Series>
         </Series>
         <ChartAreas>
             <asp:ChartArea Name="ChartArea1">
             </asp:ChartArea>
         </ChartAreas>
     </asp:Chart>
     <asp:Chart ID="Chart2" runat="server" BackImageAlignment="TopRight" Height="291px" Width="646px">
        <Titles>
        <asp:Title Font="Times New Roman, 12pt, style=Bold, Italic" Name="Title1" 
            Text="CUstomers based on Region in Pie Chart">
        </asp:Title>
    </Titles>
         <Series>
             <asp:Series Name="Series1">
             </asp:Series>
         </Series>
         <ChartAreas>
             <asp:ChartArea Name="ChartArea1">
             </asp:ChartArea>
         </ChartAreas>
     </asp:Chart>
     <br /><br />
     <asp:Chart ID="Chart3" runat="server" Width="603px">
         <Titles>
        <asp:Title Font="Times New Roman, 12pt, style=Bold, Italic" Name="Title1" 
            Text="Revenue Generated by Employees">
        </asp:Title>
    </Titles>
         <Series>
             <asp:Series Name="Series1">
             </asp:Series>
         </Series>
         <ChartAreas>
             <asp:ChartArea Name="ChartArea1">
             </asp:ChartArea>
         </ChartAreas>
     </asp:Chart>
&nbsp;&nbsp;
     <asp:Chart ID="Chart4" runat="server" Width="597px">
         <Titles>
        <asp:Title Font="Times New Roman, 12pt, style=Bold, Italic" Name="Title1" 
            Text="Revenue Generated by Employees">
        </asp:Title>
    </Titles>
         <Series>
             <asp:Series Name="Series1">
             </asp:Series>
         </Series>
         <ChartAreas>
             <asp:ChartArea Name="ChartArea1">
             </asp:ChartArea>
         </ChartAreas>
     </asp:Chart>
     <br />
     <br />
     
</asp:Content>




 